# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Jingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jnome', models.CharField(max_length=60)),
                ('jautor', models.CharField(max_length=60)),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('texto', models.CharField(max_length=500)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcastWebPolls.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=500)),
                ('jingle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcastWebPolls.Jingle')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=60)),
                ('senha', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jingle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcastWebPolls.Jingle')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcastWebPolls.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='mensagem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcastWebPolls.Usuario'),
        ),
        migrations.AddField(
            model_name='jingle',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcastWebPolls.Usuario'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='jingle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcastWebPolls.Jingle'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcastWebPolls.Usuario'),
        ),
    ]
